name: Deployment
on:
  push:
    branches:
      - main
permissions:
  contents: read
  deployments: write
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run checks
        run: |
          npm run check
          npm run lint
          npm run format:check

      - name: Run tests
        run: npm test

      - name: Run build
        run: npm run build

      - name: Deploy to Netlify
        run: npx netlify-cli deploy --dir=dist --prod
        env:
          NETLIFY_SITE_ID: ${{ vars.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
